import { pageInformation, Routes } from 'constants/pages'

import { tags } from './tags'

export const caseStudies = [
  {
    key: 'tempso',
    client: 'Tempso',
    year: '2019',
    platform: 'native (IOS & ANDROID)',
    title: 'Designing a Classical Music Streaming App',
    description:
      'Designed a classical music streaming application fully integrated with Apple Music and Spotify.',
    href: pageInformation[Routes.TempsoUX]!.path,
    src: '/ux-case-study-tempso.png',
    alt: 'Tempso UX Case Study',
    external: false,
    tags: [tags.mobile, tags.design],
    projectType: 'design',
    metrics: [
      '2020',
      'user research, user experience, user interface',
      'user interviews, wireframing, usability studies',
      'native IOS & android',
      'miro mindmapping, octopus sitemap, figma',
    ],
    latest: true,
  },
  {
    key: 'bluecargo_dashboard',
    client: 'BlueCargo',
    year: '2022',
    platform: 'desktop',
    title: 'Designing a Container Management Dashboard',
    description:
      'Designed a dashboard for Supply Chain professionals, where they can follow the status of their containers at the ports of Los Angeles and Long Beach.',
    href: pageInformation[Routes.ContainerDashboard]!.path,
    src: '/case-study-container-management.png',
    alt: 'Container Tracking Case Study',
    external: false,
    tags: [tags.desktop, tags.design],
    projectType: 'design',
    latest: true,
  },
  {
    key: 'bluecargo_payment',
    client: 'BlueCargo',
    year: '2022',
    platform: 'desktop',
    title: 'Designing a checkout flow',
    description:
      'Designed a checkout flow for a Supply Chain software, where users have a choice between three plans, and can adjust their volume per plan.',
    href: pageInformation[Routes.ContainerDashboard]!.path,
    src: '/case-study-payment-plan.png',
    alt: 'Checkout Flow Case Study',
    external: false,
    tags: [tags.desktop, tags.design],
    projectType: 'design',
    latest: true,
  },
  {
    key: 'kbwf',
    client: 'Know Better World Foundation',
    year: '2020',
    platform: 'desktop',
    title: 'Designing and building a website for a Foundation',
    description:
      'Designed and build a website for a foundation emporing women to become entrepeneur.',
    href: 'https://www.knowbetterworldfoundation.org/',
    src: '/case-study-kbwf.png',
    alt: 'Know Better World Foundation Website',
    external: true,
    tags: [tags.desktop, tags.web, tags.branding],
    projectType: 'design',
    latest: false,
  },
  {
    key: 'skoog',
    client: 'Skoog Media',
    year: '2020',
    platform: 'desktop',
    title: 'Designing and Building a Shopify Store for an interactive toy',
    description:
      'Redesigned a Shopify Store for an early-stage EduTech startup, seeking to scale the sales of a new,  interactive toy for kids.',
    href: 'https://skoog.media/',
    src: '/case-study-skoog.png',
    alt: 'Skoog Website',
    external: true,
    tags: [tags.desktop, tags.web, tags.branding],
    projectType: 'design',
    latest: false,
  },
  {
    key: 'technext',
    client: 'Technext',
    year: '2020',
    platform: 'desktop',
    title: 'Designing a website for a tech startup',
    description:
      'Redesigned the website for a deep tech startup involved in EduTech and GreenTech technologies.',
    href: 'https://www.technext.fr/?lang=en',
    src: '/case-study-technext.png',
    alt: 'Technext Website',
    external: true,
    tags: [tags.desktop, tags.web, tags.branding],
    projectType: 'design',
    latest: false,
  },
  {
    key: 'ui_shots',
    client: 'UI Shots',
    year: '2020',
    platform: 'desktop and mobile',
    title: '100 days of UI Challenge',
    description: 'Designed UI shots to explore different design universe.',
    href: pageInformation[Routes.UIShots]!.path,
    src: '/case-study-ui-shots.png',
    alt: 'UI Shots',
    external: false,
    tags: [tags.desktop, tags.mobile, tags.branding],
    projectType: 'design',
    latest: false,
  },
  {
    key: 'portfolio_website',
    client: 'Portfolio Website',
    year: '2022',
    platform: 'responsive web',
    title: 'Designed and built my own portfolio website.',
    description:
      'Designed and built the front-end and back-end of my portfolio website using Next.js, React.js, Node.js, Tailwind CSS, Mongoose and MongodB.',
    href: 'https://github.com/PierreParienteDimitrov/pierre-parientedimitrov',
    src: '/software-portfolio.png',
    alt: 'Portfolio Website',
    external: true,
    tags: [tags.software],
    projectType: 'software',
    latest: false,
  },
  {
    key: 'tempso_website',
    client: 'Tempso Landing Page',
    year: '2021',
    platform: 'responsive web',
    title: 'Designed and built Tempso landing page.',
    description:
      'Designed and built Tempso landing page using Next.js, React.js and Tailwind CSS.',
    href: 'https://github.com/PierreParienteDimitrov/tempso.com',
    src: '/case-study-tempso-landing-page.png',
    alt: 'Tempso Landing Page',
    external: true,
    tags: [tags.software],
    projectType: 'software',
    latest: false,
  },
]
