import { pageInformation, Routes } from 'constants/pages'

import { tags } from './tags'

export const caseStudies = [
  {
    project: 'Tempso',
    year: '2019',
    platform: 'native (IOS & ANDROID)',
    title: 'Designing a Classical Music Streaming App',
    description:
      'Designed a classical music streaming application for, fully integrated with Apple Music and Spotify.',
    href: pageInformation[Routes.TempsoUX]!.path,
    src: '/ux-case-study-tempso.png',
    alt: 'Tempso UX Case Study',
    external: false,
    tags: [tags.mobile, tags.ur, tags.ux, tags.ui],
  },
  {
    project: 'BlueCargo',
    year: '2021',
    platform: 'desktop',
    title: 'Designing a Supply Chain Software',
    description:
      'Designed a dashboard for Supply Chain professionals, where they can follow the status of their containers at the ports of Los Angeles and Long Beach.',
    href: pageInformation[Routes.ContainerTracking]!.path,
    src: '/case-study-container-management.png',
    alt: 'Container Tracking Case Study',
    external: false,
    tags: [tags.desktop, tags.ur, tags.ux, tags.ui],
  },
  {
    project: 'Know Better World Foundation',
    year: '2020',
    platform: 'desktop',
    title: 'Designing and building a website for a Foundation',
    description:
      'Designed and build a website for a foundation emporing women to become entrepeneur.',
    href: 'https://www.knowbetterworldfoundation.org/',
    src: '/case-study-kbwf.png',
    alt: 'Know Better World Foundation Website',
    external: true,
    tags: [tags.desktop, tags.ux, tags.ui, tags.websiteBuilder],
  },
  {
    project: 'Skoog Media',
    year: '2020',
    platform: 'desktop',
    title: 'Designing and Building a Shopify Store for an interactive toy',
    description:
      'Redesigned a Shopify Store for an early-stage EduTech startup, seeking to scale the sales of a new,  interactive toy for kids.',
    href: 'https://skoog.media/',
    src: '/case-study-skoog.png',
    alt: 'Skoog Website',
    external: true,
    tags: [tags.desktop, tags.ux, tags.ui, tags.websiteBuilder],
  },
  {
    project: 'Technext',
    year: '2020',
    platform: 'desktop',
    title: 'Designing a website for a tech startup',
    description:
      'Redesigned the website for a deep tech startup involved in EduTech and GreenTech technologies.',
    href: 'https://www.technext.fr/?lang=en',
    src: '/case-study-technext.png',
    alt: 'Technext Website',
    external: true,
    tags: [tags.desktop, tags.ux, tags.ui, tags.websiteBuilder],
  },
  // {
  //   project: 'Tempso UI',
  //   description: 'UI & High-fidelity mockups',
  //   href: pageInformation[Routes.Tempso]!.path,
  //   src: '/case-study-tempso.png',
  //   alt: 'Tempso UI',
  //   external: false,
  //   tags: [tags.ui],
  // },
  // {
  //   project: 'Luxury Travel Agency',
  //   description: 'UX/UI Design - Website',
  //   href: pageInformation[Routes.LuxuryTravel]!.path,
  //   src: '/case-study-luxury-travel.png',
  //   alt: 'Luxury Travel Case Study',
  //   external: false,
  //   tags: [tags.ux, tags.ui, tags.branding],
  // },
  {
    project: 'UI Shots',
    year: '2020',
    platform: 'desktop and mobile',
    title: '100 days of UI Challenge',
    description: 'Designed UI shots to explore different design universe.',
    href: pageInformation[Routes.UIShots]!.path,
    src: '/case-study-ui-shots.png',
    alt: 'UI Shots',
    external: false,
    tags: [tags.desktop, tags.mobile, tags.ui],
  },
  {
    project: 'Portfolio Website',
    year: '2020',
    platform: 'desktop and mobile',
    title: 'Designed and built my own portfolio website.',
    description:
      'Designed and built the front-end and back-end of my portfolio website using Next.js, React.js, Node.js, Tailwind CSS and MongodB.',
    href: 'https://github.com/PierreParienteDimitrov/pierre-parientedimitrov',
    src: '/software-portfolio.png',
    alt: 'Portfolio Website',
    external: true,
    tags: [tags.frontEnd, tags.backEnd, tags.fullStack],
  },
  {
    project: 'Tempso Landing Page',
    year: '2020',
    platform: 'desktop and mobile',
    title: 'Designed and built Tempso landing page.',
    description:
      'Designed and built Tempso landing page using Next.js, React.js and Tailwind CSS.',
    href: 'https://github.com/PierreParienteDimitrov/tempso.com',
    src: '/case-study-tempso-landing-page.png',
    alt: 'Tempso Landing Page',
    external: true,
    tags: [tags.desktop, tags.ux, tags.ui, tags.frontEnd],
  },
]
